mdapioutput/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerGlobalId__c</fullName>
        <externalId>true</externalId>
        <label>Customer Global Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/unpackaged/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Product_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VehicleIdentificationNumber__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle Identification Number</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/unpackaged/objects/VehicleOwnership__c.object
<CustomObject>
    <fields>
        <fullName>Account_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Ownerships</relationshipLabel>
        <relationshipName>Vehicle_Ownerships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ref__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Ownerships</relationshipLabel>
        <relationshipName>Vehicle_Ownerships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vehicle Ownership</label>
    <nameField>
        <displayFormat>VO{000000000}</displayFormat>
        <label>Vehicle Ownership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Ownerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapioutput/classes/Vehicle_ListingController.cls
public with sharing class Vehicle_ListingController {
   
    @AuraEnabled
    public static List<Case> getCasesForVehicle(Id vehicleId) {
        return [select Id, ContactId, Subject, Priority from Case where VehicleOwnership_ref__r.Vehicle_ref__c=:vehicleId order by createdDate DESC limit 5];
    }
    
    @AuraEnabled
    public static List<Vehicle__c> getAllVehicles(Id parentId) {
        // Attachment permissions are set in parent object (Contact)
        if (!Schema.sObjectType.Vehicle__c.isAccessible()) {
            throw new System.NoAccessException();
        }
        
        return [select 
                VehicleIdentificationNumber__c, 
                Product_ref__r.Name, 
                Product_ref__r.Brand__c,
                Product_ref__r.Model__c,
                Product_ref__r.Picture__c,
                Product_ref__r.Year__c
                from 
                Vehicle__c 
                where Id in 
                (select Vehicle_ref__c from VehicleOwnership__c where Account_ref__c =: parentId)];
    }
    @AuraEnabled
    public static List<Vehicle__c> getAllVehiclesLead(String customerGlobalId) {
        // Attachment permissions are set in parent object (Contact)
        if (!Schema.sObjectType.Vehicle__c.isAccessible()) {
            throw new System.NoAccessException();
        }
        Account acc = [Select Id from Account where CustomerGlobalId__c =: customerGlobalId];
        if(acc != null)
        return [select 
                VehicleIdentificationNumber__c, 
                Product_ref__r.Name, 
                Product_ref__r.Brand__c,
                Product_ref__r.Model__c,
                Product_ref__r.Picture__c,
                Product_ref__r.Year__c
                from 
                Vehicle__c 
                where Id in 
                (select Vehicle_ref__c from VehicleOwnership__c where Account_ref__c =: acc.Id)];
         else
                 return new List<Vehicle__c>();
    }
}