mdapioutput/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerGlobalId__c</fullName>
        <externalId>true</externalId>
        <label>Customer Global Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalaryOrientation__c</fullName>
        <label>Salary Orientation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/unpackaged/objects/CustomerProfile__c.object
<CustomObject>
    <fields>
        <fullName>AssignedDealership_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Dealership</label>
        <referenceTo>Dealership__c</referenceTo>
        <relationshipLabel>Customer Profiles</relationshipLabel>
        <relationshipName>CustomerProfiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillingCity__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountry__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingPostalCode__c</fullName>
        <label>Billing Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingStreet__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerGlobalId__c</fullName>
        <externalId>true</externalId>
        <label>Customer Global Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerProfileGlobalExternalId__c</fullName>
        <externalId>true</externalId>
        <label>Customer Profile Global External Id</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles</relationshipLabel>
        <relationshipName>Customer_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalaryOrientation__c</fullName>
        <label>Salary Orientation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SyncStatus__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Synced</fullName>
                </value>
                <value>
                    <fullName>Pending for Sync</fullName>
                </value>
                <value>
                    <fullName>Unsynced</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Pending for Unsync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP{000000000}</displayFormat>
        <label>Customer Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/classes/OEM_CustomerProfileService.cls
public class OEM_CustomerProfileService {
    public static void assignGlobalId(List<sObject> scope){
        for(sObject rec : scope){
            if( String.isEmpty((String)rec.get('CustomerProfileGlobalExternalId__c'))) 
                rec.put('CustomerProfileGlobalExternalId__c', GuidUtil.NewGuid());
        }
    }
    public static void copyFieldFromAccount(List<CustomerProfile__c> scope){
        Map<Id, Account> accountCache = new Map<Id, Account>();
        for(CustomerProfile__c cp : scope){
            if(String.isEmpty( cp.Customer_ref__c)){
                cp.Customer_ref__c.addError('Customer reference cannot be null');
                continue;
            }
            if(String.isEmpty( cp.AssignedDealership_ref__c)){
                cp.AssignedDealership_ref__c.addError('Assigned Dealership reference cannot be null');
                continue;
            }
            accountCache.put(cp.Customer_ref__c, null);  
        }
        if(!accountCache.isEmpty()){
            accountCache = new Map<ID, Account>([Select Id, FirstName, LastName, Industry, BillingCity, BillingCountry, BillingPostalCode, BillingStreet,SalaryOrientation__c , CustomerGlobalId__c  From Account where Id =: accountCache.keySet()]);
            for (CustomerProfile__c cp : scope) {
                Account acc = accountCache.get( cp.Customer_ref__c);
                if( acc != null ) {
                    if( String.isEmpty(cp.SyncStatus__c) ) cp.SyncStatus__c = 'Pending for Sync';
                    
                    cp.BillingCity__c = acc.BillingCity;
                    cp.BillingCountry__c = acc.BillingCity;
                    cp.BillingPostalCode__c = acc.BillingPostalCode;
                    cp.BillingStreet__c = acc.BillingStreet;
                    cp.CustomerGlobalId__c = acc.CustomerGlobalId__c;
                    cp.FirstName__c = acc.FirstName;
                    cp.LastName__c = acc.LastName;
                    cp.SalaryOrientation__c = acc.SalaryOrientation__c;
                    cp.Industry__c = acc.Industry;
                    
                }else{
                    cp.Customer_ref__c.addError('Could not query account for copy');
                }
            }
        }
    } 
}