mdapioutput/unpackaged/objects/CustomerProfile__c.object
<CustomObject>
    <fields>
        <fullName>AssignedDealership_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Dealership</label>
        <referenceTo>Dealership__c</referenceTo>
        <relationshipLabel>Customer Profiles</relationshipLabel>
        <relationshipName>CustomerProfiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles</relationshipLabel>
        <relationshipName>Customer_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SyncStatus__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Synced</fullName>
                </value>
                <value>
                    <fullName>Pending for Sync</fullName>
                </value>
                <value>
                    <fullName>Unsynced</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Pending for Unsync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP{000000000}</displayFormat>
        <label>Customer Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/unpackaged/objects/Dealership__c.object
<CustomObject>
    <label>Dealership</label>
    <nameField>
        <label>Dealership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/classes/Account_ManageCustomerProfileController.cls
public class Account_ManageCustomerProfileController {
	@AuraEnabled
    public static List<CustomerProfile__c> getPersonAccounts(Id masterAccountId){
        return [SELECT Name, Customer_ref__r.Name, AssignedDealership_ref__r.Name, SyncStatus__c FROM CustomerProfile__c where Customer_ref__c = :masterAccountId];
    }
    
    @AuraEnabled
    public static void updateCustomerProfiles(List<CustomerProfile__c> customerProfiles) {
        List<CustomerProfile__c> toUpdate = new List<CustomerProfile__c>();
        for(CustomerProfile__c customerProfile: customerProfiles) {
            toUpdate.add(new CustomerProfile__c(Id=customerProfile.Id, SyncStatus__c = customerProfile.SyncStatus__c));
        }
        if(!toUpdate.isEmpty()){
            update toUpdate;
            externalCallout();
        }
    }
    @future(callout=true)
    public static void externalCallout(){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:Cloudhub_CustomerProfile/api/trigger');
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8'); 
        HttpResponse response = http.send(request);
    }
}